import React from 'react';
import css from './Datenschutz.css';

export default function Datenschutz() {
    return (
        <div className='Datenschutz'>
            <h2 className='text1'>
                <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quae, libero expedita voluptatibus, ex quo cupiditate repellat odit, non facere maxime repudiandae ut dolorem esse maiores! Corporis minus quaerat facilis debitis cupiditate dolorem officiis atque doloremque voluptatibus laborum! Soluta dolore a autem culpa enim vero obcaecati optio distinctio sapiente inventore. Vel ipsam dolor cumque sequi fugit possimus temporibus! Commodi quod ullam odio cupiditate obcaecati laudantium magni quam accusamus quaerat, nostrum quasi dolore, rerum ex, reiciendis iusto veniam. Facere assumenda fugiat asperiores soluta quae nemo nostrum esse? Iusto illum labore ut soluta expedita aliquid accusamus impedit qui velit? Porro, nulla architecto assumenda quasi distinctio natus quaerat quibusdam, recusandae mollitia ratione quos ducimus incidunt sit! Doloremque alias amet est sint, consequatur dolorum sapiente perferendis veniam ad minima eligendi repellat eaque laboriosam quos provident, id ipsum quibusdam deleniti. Eveniet atque, non est doloremque voluptatum amet nesciunt reiciendis architecto saepe consequatur voluptates, assumenda sed! Blanditiis distinctio assumenda optio, magnam atque non veniam, voluptatem culpa adipisci ea enim sed itaque tempora ducimus quas voluptates quaerat. Fugit excepturi impedit, at placeat consequatur ullam ab magni maxime odit eos expedita velit quas temporibus! Praesentium veritatis sit, deserunt aperiam officia nisi consequatur minus nihil voluptates omnis. Eveniet excepturi illo ut facilis vero quo accusantium explicabo magnam, itaque quidem. Ipsum ea magnam consequatur voluptatibus quisquam modi dolorum aut nisi obcaecati unde mollitia, excepturi exercitationem porro aliquam tenetur architecto natus? Nostrum, sunt facere blanditiis hic delectus eligendi autem, cupiditate modi voluptatum, molestias voluptate quod. Quaerat corrupti autem aut consequuntur, exercitationem magnam libero voluptatem incidunt odio soluta laborum labore. Commodi, debitis pariatur? Neque officiis consequuntur, nobis illum, eius perspiciatis illo vitae molestiae nesciunt saepe voluptatibus quas! Rerum voluptatum, ex unde ab maiores iste. Nisi nemo exercitationem maiores. Aliquid voluptates debitis corrupti magnam maiores delectus sapiente sunt iste, et harum cupiditate eligendi quas.
                </p>
            </h2>
        </div>
    )
}